[project]
authors = [{ name = "Moye", email = "moyeodiase@outlook.com" }]

name = "mnist-numpy"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = "<4.0,>=3.11"
dependencies = [
  "numpy<3.0.0,>=2.2.3",
  "more-itertools<11.0.0,>=10.6.0",
  "pandas<3.0.0,>=2.2.3",
  "matplotlib<4.0.0,>=3.10.1",
  "tqdm<5.0.0,>=4.67.1",
  "click<9.0.0,>=8.1.8",
  "loguru<1.0.0,>=0.7.3",
]

[dependency-groups]
dev = ["ruff<1.0.0,>=0.9.7"]

[uv.tool]
default-groups = []